[tool.poetry]
name = "tg-parser"
version = "0.1.0"
description = ""
authors = ["author"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pyrogram = "^2.0.106"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
